// Approved local-only content revision. Candidate phrases are not service promises.
import {load} from 'cheerio';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(route,label)=>`<a href="/${route ? route+'/' : ''}">${esc(label)} →</a>`;
const paragraphs=items=>items.map(p=>`<p>${esc(p)}</p>`).join('');
const block=(title,body)=>`<section class="section content-intent"><div class="container"><h2>${esc(title)}</h2>${body}</div></section>`;
// Each service owns a different decision, rather than a list of keyword variants.
export const serviceIntents={
 'roof-repairs':{heading:'Small roof repairs without an unnecessary wider scope.',q:'Can I arrange a local repair rather than a full restoration?',a:'Yes. A defined tile, metal, ridge or flashing defect can be assessed for a local repair. We check the surrounding material before setting the scope; a small visible defect can connect with other damage. Cleaning or painting is a separate decision, not a condition of every repair.',next:'For a rental property, include the tenant or access contact and who can approve the work. Ask for the repair items, access, materials, removal of waste and exclusions to be clear in the quote. Any warranty terms should be confirmed in writing for that scope, rather than assumed from a general website statement.',guide:'roof-leak-inspection',label:'Understand the inspection and repair decision'},
 'roof-leak-repairs':{heading:'Recurring leaks, ceiling stains and repairs near equipment.',q:'What if a leak appeared after solar panels were installed?',a:'Tell us when the solar installation and the first leak occurred, and share any earlier repair records. Timing alone does not establish the cause. The roof covering, fixings, penetrations and connected drainage need assessment; electrical equipment must be handled by the appropriate specialist.',next:'A ceiling stain is a starting point, not proof of a particular defect. Note whether water appears in heavy rain, wind-driven rain or dry weather. Water can travel before becoming visible indoors. Where condensation, plumbing or equipment is suspected, the next step may involve another trade rather than a roof patch. Include previous sealant work if the same area is leaking again.',guide:'roof-leak-detection-perth',label:'Read about tracing a leak that returns'},
 'tile-roof-repairs':{heading:'Individual tile replacement and matching the existing roof.',q:'Can broken concrete or terracotta tiles be replaced individually?',a:'Individual replacement can suit local damage where the surrounding tiled roof remains serviceable. The replacement needs a compatible profile and fit; colour alone is not enough. Older tile availability needs checking before a matching replacement can be confirmed.',next:'Tell us whether tiles are cracked, missing or displaced, and whether water has appeared inside. Do not climb onto the roof to identify a profile. For a two-storey home, mention the roof level, driveway and side access so suitable access arrangements can be assessed before work is booked.',guide:'tile-roof-repairs-perth-guide',label:'Compare cracked-tile and adjoining-junction repairs'},
 'metal-roof-repairs':{heading:'Local metal roof work before whole-sheet replacement.',q:'Can screws and flashings be repaired without replacing every sheet?',a:'A local fixing or flashing repair may be suitable when the surrounding sheet remains sound. We assess the washer, fixing hole, sheet condition and connected laps together. Where corrosion or damage extends beyond the fixing, the affected sheet or formed component may need replacement.',next:'Corrugated, tin and COLORBOND are terms customers use to describe metal roofs. The actual profile, coating and material compatibility need checking before repair materials are selected. Mention rattling sheets, visible rust and previous screw work. A material name does not imply manufacturer authorisation or a universal repair method.',guide:'metal-roof-repairs-perth-guide',label:'See how screws, washers and sheets are assessed'},
 'ridge-capping-repointing':{heading:'Know which ridge repair your quote includes.',q:'What is the difference between repointing and rebedding?',a:'Pointing is the exposed finish at the ridge cap joints; bedding supports the caps beneath it. Repointing renews the relevant finish. Rebedding addresses the supporting bed where its condition or cap stability requires it. Covering loose support with a new finish does not address the underlying problem.',next:'A ridge quote should identify the affected ridge or hip runs, any damaged caps or adjoining tiles, the bedding and pointing work, and access. Cracks or fallen mortar are useful observations, but inspection determines the work needed. Ask which components are being retained and which are being renewed.',guide:'ridge-capping-repairs-perth-guide',label:'Compare repointing, rebedding and cap replacement'},
 'flashing-repairs':{heading:'Separate roof junction defects from equipment faults.',q:'Is water around a skylight always a flashing problem?',a:'No. Water can involve the skylight unit, its flashing, adjoining roof covering or another nearby source. The location of the indoor mark does not distinguish them. We assess the roof junction within our repair scope and explain when the unit or equipment needs a separate specialist.',next:'The same distinction matters around vents, evaporative coolers and roof-to-wall connections. Include the affected opening and when water appears. A valley with leaves may need clearing, while deteriorated valley iron can need component work. We separate debris removal from repair or replacement of damaged metal.',guide:'roof-valleys-flashing-repairs-perth',label:'Understand valley and chimney junction repairs'},
 'gutter-repairs':{heading:'Overflow is a symptom, not a complete repair scope.',q:'Does an overflowing gutter always need replacement?',a:'No. Restricted outlets, deposits, damaged joints or the condition of the gutter run can contribute to overflow. Clearing a blockage and replacing deteriorated material are different tasks. The affected run and its downpipe connection need checking before choosing the work.',next:'Record where overflow occurs and whether it coincides with indoor water marks. If your building has an internal or box gutter, identify it when enquiring so the team can confirm the appropriate scope and specialist requirements before booking. Do not assume an external gutter repair covers every drainage system.',guide:'gutter-warning-signs',label:'Read the gutter overflow and joint warning signs'},
 'gutters-downpipes':{heading:'Follow the whole roof drainage route.',q:'Why check a downpipe when the gutter is overflowing?',a:'Water needs a connected route from the roof edge through the outlet and downpipe. A restriction or disconnected joint downstream can affect the visible gutter problem. We consider the connected components rather than treating an overflowing section in isolation.',next:'Tell us which gutter run and downpipe are affected, what happens in rain and whether earlier clearing changed the problem. Underground stormwater, internal drainage and unrelated plumbing are not automatically included in a roof-edge repair; ask which parts of the route the proposed work covers.',guide:'drainage-after-rain',label:'Review drainage observations after rain'},
 'downpipe-repairs':{heading:'Define the damaged pipe section and its connections.',q:'Can a leaking downpipe joint be repaired locally?',a:'Local joint or section work can be considered where the remaining pipe and supports are suitable. We check the connection above and below the damaged area, including the outlet and discharge connection relevant to the repair. A visible leak does not establish the condition of concealed drainage.',next:'Include the pipe location, roof height and whether water escapes at a joint or backs up from below. Access and compatible replacement sections can affect the scope. If underground drainage needs investigation, confirm that separately rather than assuming it is included in a downpipe repair.',guide:'gutter-warning-signs',label:'Identify connected gutter and downpipe warning signs'},
 'roof-maintenance':{heading:'Plan maintenance around the condition found.',q:'What should I arrange before Perth winter rain?',a:'Start with known defects and the connected drainage route: damaged tiles or sheets, ridge connections, flashings, valleys, gutters and outlets. Inspection helps separate clearing and upkeep from component repairs. The right interval depends on the roof and its surroundings, not one schedule for every property.',next:'Share the last inspection or repair date, recurring leaf deposits and previous rain-related problems. Existing ground-level photographs can help explain the enquiry. Do not access the roof to gather evidence. Maintenance does not guarantee that a roof will remain leak-free in every future weather event.',guide:'roof-maintenance-basics',label:'Read the roof maintenance priorities'},
 'roof-cleaning-painting':{heading:'Repair defects before deciding on a surface finish.',q:'Does roof painting fix a leaking roof?',a:'Painting is a surface treatment, not a substitute for repairing cracked tiles, damaged sheets, loose connections or defective flashing. Repair needs and coating suitability should be established before preparation or finishing is agreed.',next:'Ask the quote to distinguish repairs, cleaning, preparation and the proposed finish. Existing material and coating condition affect what can be used. If your priority is a leak rather than appearance, start with a leak assessment and decide on any broader surface work separately.',guide:'roof-maintenance-basics',label:'Separate maintenance from component repairs'},
 'commercial-roof-repairs':{heading:'Coordinate roof repairs with the people using the building.',q:'What information helps plan a commercial roof inspection?',a:'Include the affected tenancy, roof level, access contact, operating hours and any restricted areas or equipment near the problem. Identify who can approve the work. These details help assess access and define the repair scope before scheduling.',next:'Ask whether the proposed records and quote meet your building manager’s requirements before booking. Roof repair observations are not automatically an insurance determination, engineering assessment or full building report. Shared or strata responsibility must be clarified with the authorised decision-maker.',guide:'roof-inspection-perth-guide',label:'Review inspection scope and repair priorities'},
 'storm-damage-roof-repairs':{heading:'Urgent assessment and permanent repair are different steps.',q:'Can you guarantee a visit today after storm damage?',a:'Contact us to discuss the current situation and availability. Attendance depends on the location, weather, access and whether roof work can be carried out safely. Our opening hours are Monday–Sunday, 9am–9pm Perth local time; these are not a guarantee of an immediate roof visit.',next:'Keep people away from the affected area and describe active water entry or displaced materials when calling. Temporary protection, inspection and permanent repairs may need separate arrangements. Tell us if your insurer needs particular records; a repair enquiry does not guarantee a claim outcome.',guide:'roof-leak-inspection',label:'Understand the assessment before repair work'},
 'roof-restoration':{heading:'Restoration starts with the repairs, not the paint.',q:'How is restoration different from a local roof repair?',a:'A local repair addresses identified defects in a defined area. Restoration coordinates a wider set of suitable repairs and any agreed preparation or finishing. The inspected condition determines whether that wider scope adds value; appearance alone does not identify a leak repair.',next:'Compare the repair components, drainage work, access, preparation and finishing listed in the quote. Ask which items are optional and which address the defects. If only one component needs attention, discuss the targeted repair before committing to broader work.',guide:'roof-inspection-perth-guide',label:'Use inspection findings to choose the scope'},
 'roof-inspection':{heading:'Confirm inspection fees, records and scope before booking.',q:'Is the inspection fee separate from the repair quote?',a:'Confirm the inspection fee and what it includes with our team before you book. Also ask whether any inspection charge is separate from the repair work or credited against an accepted quote. This website does not publish a universal inspection fee or assume that every inspection is free.',next:'Explain whether you need photographs, written repair recommendations or a particular report format. Confirm what can be supplied for your property before booking. A roof condition inspection is not automatically a pre-purchase building inspection, structural assessment or insurance report. Access limitations should be recorded alongside the findings.',guide:'roof-inspection-perth-guide',label:'See the components a roof inspection considers'},
 'repair-options':{heading:'Repair, restoration or replacement: decide from evidence.',q:'When should wider replacement be considered?',a:'Widespread deterioration, several connected defects or material that can no longer support an appropriate local repair may justify a wider assessment. Whole-roof replacement is a separate scope from replacing an affected tile or metal sheet; do not assume it is included in a local repair quote.',next:'Ask for the defects behind the recommendation, what can be retained and the limits of each option. A second assessment can help when the proposed extent is unclear. Coating or repeated sealant should not be treated as a universal alternative to correcting damaged components.',guide:'roof-leak-inspection',label:'Start with the inspection evidence'}
};

const areaNotes={
 cottesloe:['Which roof edge or junction is affected?','For a property near the coast, mention visible corrosion if you have already noticed it. Exposure is useful context, not proof that every fixing or sheet needs replacement.','metal-roof-repairs'],
 'mosman-park':['Does the leak affect the main roof or an addition?','Identify the original roof, any extension and the connection between them. A mark near a wall can involve the junction or another uphill roof detail; record the rain conditions rather than assuming the source.','flashing-repairs'],
 'city-beach':['Is the problem at the roof edge or further uphill?','Describe the affected gutter run, outlet and nearby roof junction. Water at the eave can need a connected roof and drainage assessment rather than a gutter patch alone.','gutters-downpipes'],
 scarborough:['Are rust marks confined to a few metal fixings?','Mention whether you have noticed rust at isolated screws or across a larger sheet area. Existing photographs help describe the concern, but local repair suitability depends on the surrounding material.','metal-roof-repairs'],
 claremont:['Do damaged tiles need matching before replacement?','Include the tile material and any spare-tile information you already have. For an older tiled roof, a compatible profile needs checking; neither a similar colour nor the age of the house settles the repair method.','tile-roof-repairs'],
 nedlands:['Is water appearing beside a chimney or wall?','Identify the affected room and the nearby roof-to-masonry junction if known. The roof covering and flashing need consideration together; a ceiling mark is not proof that the chimney is the source.','flashing-repairs'],
 subiaco:['What access is available for the affected roof level?','For a two-storey property or constrained side access, include the roof level, driveway and adjoining structures. Suitable equipment and permission requirements need assessment before a visit can be confirmed.','roof-leak-repairs'],
 perth:['Who can authorise access to the building roof?','For a CBD tenancy, provide the building manager or authorised access contact and any induction or operating-hour restrictions. Identify the affected roof level so a repair enquiry is not based only on the room below.','commercial-roof-repairs'],
 leederville:['Does the affected junction connect to an extension?','Include whether the issue is on the original building, an added roof or their meeting point. Mention access near adjoining structures and who can authorise any shared-area access.','flashing-repairs'],
 joondalup:['Did earlier repair or clearing change the leak?','Share the previous scope and whether the problem returned in the same rain conditions. This helps distinguish recurring water entry from an unrelated new defect, without assuming another sealant patch is the answer.','roof-leak-repairs'],
 hillarys:['Does water appear only when rain comes with wind?','Note the affected room, timing and wind-driven rain pattern if known. Compare this with lighter rain events. The weather pattern helps direct inspection but does not diagnose a particular flashing or roof slope.','roof-leak-repairs'],
 fremantle:['Can the existing terracotta tiles be matched?','If your property has older terracotta tiles, include existing material records or safely obtained photos. Matching and local replacement depend on profile and availability, not a promise that every older tile can be sourced.','tile-roof-repairs'],
 rockingham:['Is the concern local corrosion or an active leak?','Describe visible rust separately from water entering indoors and mention any earlier fixing work. Coastal location provides context; the actual sheets, fixings and junctions determine the scope.','metal-roof-repairs'],
 kalamunda:['Are leaf deposits recurring at valleys or outlets?','Mention the affected drainage route and when it was last cleared, if known. Deposits call for assessment of flow and material condition; clearing alone does not repair corroded valley metal or damaged tiles.','roof-maintenance'],
 'victoria-park':['Which roof-to-wall connection is near the water mark?','Describe whether the affected room is beneath the main roof, a patio connection or an extension. Ask the team to confirm the relevant junction is within scope before booking; equipment or plumbing may need a separate trade.','flashing-repairs'],
 bayswater:['Does the roof share a drainage or access route?','Identify the affected building or extension, any shared outlet and the person who can authorise access. Do not assume that a shared route establishes responsibility for the defect or permission to work on another property.','gutters-downpipes']
};
const guideServices={
 'metal-roofing-perth':'metal-roof-repairs','gutter-warning-signs':'gutter-repairs','roof-leak-inspection':'roof-inspection','roof-maintenance-basics':'roof-maintenance','roof-flashing-explained':'flashing-repairs','drainage-after-rain':'gutters-downpipes',
 'roof-leak-detection-perth':'roof-leak-repairs','tile-roof-repairs-perth-guide':'tile-roof-repairs','metal-roof-repairs-perth-guide':'metal-roof-repairs','ridge-capping-repairs-perth-guide':'ridge-capping-repointing','roof-valleys-flashing-repairs-perth':'flashing-repairs','roof-inspection-perth-guide':'roof-inspection'
};
const hubCopy={
 '':['Start with the problem you have noticed.','A ceiling stain after rain, broken tiles or a loose metal-roof detail calls for an assessment of the affected components. Our Perth team carries out targeted roof repairs and explains any connected work before the scope is agreed. You do not need to choose a whole-roof treatment to start an enquiry.',['roof-leak-repairs','Investigate a roof leak'],['repair-options','Compare local repair with wider roof work']],
 services:['Not sure which roof repair service fits?','Start with leak repairs if water is entering and the cause is unclear. Choose a material or component service when you already know the affected part. Inspection establishes the condition; maintenance, local repairs and restoration are different work scopes.',['roof-leak-repairs','Start with water-entry investigation'],['roof-inspection','Arrange a roof condition assessment']],
 'service-areas':['Confirm the location and access before arranging a visit.','Send your suburb or postcode, the affected roof level and the problem you have noticed. The Perth office is our team base, not a separate branch address in every suburb. Visit arrangements depend on the property, access and current availability.',['contact','Discuss your property location'],['roof-repairs','Review our tile and metal repair work']],
 gallery:['Use the project detail to compare the work, not just the finish.','Each linked record describes photographed roof components and the work recorded for that project. Look for a similar material or junction, then discuss the condition of your own roof. A completed photograph is not a price guide or a guarantee of the same outcome at another property.',['metal-roof-repairs','Explore fixing, sheet and capping repairs'],['flashing-repairs','Explore valley and flashing repairs']],
 news:['Find the explanation, then choose the next step.','For recurring water entry, begin with the leak-detection guide. For a known broken tile, metal fixing or ridge defect, use the matching material guide. The guides explain decisions; the service pages describe the work and how to arrange it.',['news/roof-leak-detection-perth','Understand recurring leaks after rain'],['news/roof-inspection-perth-guide','Prepare for a roof condition inspection']],
 faq:['Need an answer for your particular roof?','An answer here explains the general decision, not a diagnosis from a symptom alone. Include the roof material, suburb, timing of water entry and previous repairs when contacting the team. Leave roof access and close-up investigation to the inspection.',['contact','Send the details of your roof problem'],['news','Explore the supporting roof repair guides']],
 about:['Check who operates the service and what the records show.','Perth Roof Care is the local roof repair service operated by Ellis Services Group Pty Ltd. Our registration link identifies the operating entity; our photographed project records show particular roof-work details. These are different kinds of evidence and should be considered alongside the proposed scope for your property.',['gallery','View the photographed work records'],['contact','Discuss the team and documents for your work']],
 contact:['Before you send your roof repair enquiry.','Tell us whether the issue is an active leak, damaged component or planned maintenance. Include any previous repair history and the contact authorised to arrange access. Ask about inspection charges, the records you need and any access restrictions before a booking is confirmed.',['roof-inspection','Review inspection scope and fee questions'],['privacy','Read how enquiry information is used']],
 privacy:['Choose what to include in an enquiry.','Start with the information needed to explain the roof problem and arrange contact. Read the information above before attaching or sharing details about other occupants. Contact our team if you have a question about enquiry information.',['contact','Contact the team about enquiry information'],['legal','Read website and project information']],
 legal:['Use the guidance alongside a property-specific scope.','A general guide, material description or photograph cannot establish the condition of your roof. Review the proposed work and ask about anything unclear before accepting the scope. Company and contact information is available on the linked pages.',['about','Read about the operating company'],['contact','Clarify the proposed repair scope']]
};

export function applyContentIntent($,route){
 $('main a[href="/projects/roleystone-metal-roof-fastener-leak-repair/"]').each((_,e)=>{
  $(e).contents().each((__,node)=>{if(node.type==='text')node.data=node.data.replace(/ROYLEYSTONE/g,'ROLEYSTONE');});
 });
 const service=serviceIntents[route];
 if(service){
  const body=`<h3>${esc(service.q)}</h3>${paragraphs([service.a,service.next])}<p>${link('news/'+service.guide,service.label)} · ${link('contact','Discuss this repair and the inspection arrangements')}</p>`;
  const anchor=$('.focus-faq').first();if(anchor.length)anchor.before(block(service.heading,body));else $('main').append(block(service.heading,body));
  $('.focus-faq h2').text(`Questions about ${$('h1').text().replace(/\.$/,'').toLowerCase()}.`);
  $('.repair-delivery h2').text(`From inspection to ${route==='roof-inspection'?'repair priorities':route.replaceAll('-',' ')}.`);
 }
 const area=route.match(/^areas\/(.*)-roof-repairs$/)?.[1];
 if(areaNotes[area]){
  const [q,a,target]=areaNotes[area];
  $('main').append(block('A useful starting point for this property.',`<h3>${esc(q)}</h3>${paragraphs([a])}<p>${link(target,'Review the relevant repair scope')} · ${link('contact','Confirm the location and access arrangements')}</p>`));
 }
 const slug=route.startsWith('news/')?route.slice(5):'';
 if(guideServices[slug]){
  const target=guideServices[slug],intent=serviceIntents[target];
  $('.article-reading').append(`<section class="content-intent"><h2>Before arranging the work</h2><h3>${esc(intent.q)}</h3>${paragraphs([intent.a,intent.next])}<p>${link(target,'See the related service and work scope')} · ${link('contact','Discuss inspection arrangements')}</p></section>`);
  const h2=$('.article-reading h2');const used=new Set($('[id]').map((_,e)=>$(e).attr('id')).get());const toc=[];
  h2.each((i,e)=>{let id=`guide-section-${i+1}`;while(used.has(id))id+='-topic';used.add(id);$(e).attr('id',id);toc.push(`<li><a href="#${id}">${esc($(e).text())}</a></li>`);});
  const lead=$('.article-lead').first();const insertion=lead.length?lead:$('.article-reading > p:not(.eyebrow,.article-byline)').first();
  insertion.after(`<nav class="content-toc" aria-label="On this page"><p>On this page</p><ul>${toc.join('')}</ul></nav>`);
 }
 if(route.startsWith('projects/')){
  const matching=$('.project-services a[href^="/"]').toArray().map(e=>$(e).attr('href')).filter(h=>serviceIntents[h.replace(/^\/|\/$/g,'')]);
  const target=matching[0]?.replace(/^\/|\/$/g,'')||'roof-repairs';
  $('main').append(block('Planning similar work on your own roof?',`<p>The photographs above show this project’s roof details. Similar-looking damage can involve different surrounding material or access needs. Include the part of this record that relates to your concern, together with your suburb, roof material and any previous repair history.</p><p>${link(target,'Review the corresponding repair service')} · ${link('contact','Discuss the condition of your roof')}</p>`));
 }
 if(hubCopy[route]){const [h,p,...links]=hubCopy[route];$('main').append(block(h,paragraphs([p])+`<p>${links.map(([r,l])=>link(r,l)).join(' · ')}</p>`));}
 if(route==='faq'){
  const extra=[
   [serviceIntents['roof-inspection'].q,serviceIntents['roof-inspection'].a,'roof-inspection'],
   [serviceIntents['roof-leak-repairs'].q,serviceIntents['roof-leak-repairs'].a,'roof-leak-repairs'],
   ['Does dampness without rain always need a roof repair?','No. Condensation, plumbing or equipment can also be relevant. Note whether moisture follows rain or occurs in dry weather and explain any nearby equipment. The enquiry should be directed to the appropriate assessment rather than assuming that sealing the roof will resolve it.','roof-leak-repairs'],
   [serviceIntents['flashing-repairs'].q,serviceIntents['flashing-repairs'].a,'flashing-repairs'],
   ['What should I confirm about a repair warranty?','Ask for the terms applicable to the agreed work, including duration, covered components, exclusions and how to report a concern. Keep the accepted scope and repair records. If the area leaks again, provide the timing and previous work details so the current condition can be reviewed; do not assume a website describes the terms of your particular job.','contact'],
   ['Can I book an internal or box gutter repair from this page?','Describe the system and affected area to the team first. Blockages, outlet condition and damaged material can require different work. Scope, access and any specialist requirements need confirming; the external gutter service description does not establish that every internal drainage job is included.','gutter-repairs']
  ];
  $('.content-intent').before(block('Fees, equipment and scope questions.',`<div class="faq-list">${extra.map(([q,a,r])=>`<details><summary>${esc(q)}</summary><p>${esc(a)} ${link(r,'Discuss the related scope')}</p></details>`).join('')}</div>`));
 }
 // Retain one H1 and repair skipped levels without changing established wording.
 let previous=0;$('main h1,main h2,main h3,main h4,main h5,main h6').each((_,e)=>{let n=Number(e.tagName.slice(1));if(previous&&n>previous+1){n=previous+1;e.tagName=`h${n}`;}previous=n;});
}

export function syncContentKnowledge($,graph,site,canonical){
 // Read the serialized page with HTML entity decoding, as browsers do.
 const rendered=load($.html());
 const questions=rendered('main details').map((_,e)=>({question:rendered(e).find('summary').text(),answer:rendered(e).find('p').text()})).get();
 const existing=graph.findIndex(n=>n['@type']==='FAQPage');
 const faq={'@type':'FAQPage','@id':`${canonical}#faq`,mainEntity:questions.map(q=>({'@type':'Question',name:q.question,acceptedAnswer:{'@type':'Answer',text:q.answer}}))};
 if(questions.length){if(existing>=0)graph[existing]=faq;else graph.push(faq);}
 const knowledge=$('#page-knowledge');if(knowledge.length){const k=JSON.parse(knowledge.text());k.questions=questions;k.summary=rendered('main p:not(.eyebrow)').first().text();k.relatedUrls=[...new Set(rendered('main a[href^="/"]').map((_,e)=>site+rendered(e).attr('href').split('#')[0]).get())];knowledge.text(JSON.stringify(k).replaceAll('<','\\u003c'));}
}
