// Project facts come from supplied photographs and the existing job records.
// Publication updates are not construction dates. Keep job-specific dates unset.
export const projectStories = {
 'metal-roof-ridge-capping-repair-perth': {
  summary:'Perth metal roof ridge capping project by Ellis Services Group, showing installation, completed cap runs, fixings and the adjoining eave detail.',
  lead:'Our metal roof capping work brings the ridge, hip runs and roof-edge connections together. This project shows the installation detail and the completed grey capping across a corrugated roof.',
  topics:[
   ['A corrugated roof with connected ridge and hip lines','This roof brings several corrugated planes together beneath formed grey metal capping. The project photographs show the overall roof, a close installation view, the finished cap run and an eave connection. Together they explain the job more clearly than an isolated close-up: the repaired roof junction belongs to a continuous covering, with adjoining sheets and drainage at its edges.'],
   ['Our capping installation and fixing work','The work-stage photograph shows our tradesperson securing the formed metal capping over the corrugated roof junction. The completed views show the cap continuing along the roof line, with its fixing points visible beside the sheet profile. Our work on these connections joins the cap to the surrounding covering and gives the junction a defined, consistent finish.'],
   ['Why the cap-to-sheet connection matters','Ridge and hip capping cover the meeting point between roof planes. The formed metal, adjoining corrugations and fixing positions work together at that junction. A repair needs attention to the whole connection, including the direction of the cap run and the surrounding sheets. The close photographs make these workmanship details visible alongside the wider completed roof.'],
   ['Completed roof lines and the eave detail','The finished project shows grey capping following the ridge and hip lines, with a separate close view of the roof edge beside the gutter. These images present both the central roof junction and its surrounding roofline. For owners needing similar work, our metal roof repairs service covers capping, affected sheets, fixings and flashing connections within a coordinated repair scope.']
  ],services:['metal-roof-repairs','flashing-repairs']
 },
 'tile-roof-chimney-flashing-repair-perth': {
  summary:'Tile roof chimney flashing work by Ellis Services Group, showing the formed apron, stepped side detail and adjoining valley on a Perth roof.',
  lead:'We completed formed flashing work around this brick chimney and its adjoining tiled-roof valley. The project shows the chimney apron, side flashing and valley connection from both close and wider roof views.',
  topics:[
   ['A chimney at the meeting point of tiled slopes','The brick chimney sits beside a valley between tiled roof planes. That layout brings two important water-management details together: the metal around the chimney base and the channel carrying water through the valley. The wide project photograph establishes their position in the roof, while the close views show how the formed metal meets the adjacent tiles.'],
   ['The chimney and valley work we completed','The completed photographs show grey formed metal around the chimney, including the apron at its base and the stepped side detail against the brickwork. They also show the adjoining metal valley extending between the tiled slopes. Our work connects these details within the existing roof layout, with the photographs presenting the completed junction from several useful angles.'],
   ['An apron and side flashing with different roles','The apron is the formed metal projecting from the chimney base over the adjoining roof surface. The side flashing follows the chimney-to-roof junction along the sloping tiles. These are connected parts of the same detail, with the valley close by. The project explains why chimney work needs careful attention to both the masonry interface and the neighbouring roof covering.'],
   ['The finished chimney junction in its roof setting','The wider photographs show the completed flashing alongside the valley, tiles and nearby ridge lines. The close photographs show the apron and stepped metal detail. This combination makes the completed work easy to understand and demonstrates our focus on connected roof junctions. Our flashing repairs service handles chimney details, valleys and the adjoining tiled or metal roof connections.']
  ],services:['flashing-repairs','tile-roof-repairs','roof-leak-repairs']
 },
 'metal-roof-hip-ridge-capping-repair-perth': {
  summary:'Metal roof hip and ridge capping work by Ellis Services Group, with a formed multi-plane junction, completed cap runs and close fixing details.',
  lead:'This metal roof project centres on the intersection between hip and ridge capping. Our completed work joins the grey formed cap runs across several corrugated roof planes.',
  topics:[
   ['Several roof planes meeting at one junction','A hip-and-ridge intersection is more detailed than a straight cap run. Several roof slopes meet, and the formed metal needs to connect their changing directions. The overall photograph shows the junction in the roof layout. The closer views then identify the intersection, the continuing ridge line and the adjacent corrugated sheets that make up this project.'],
   ['Our formed hip and ridge capping work','The completed sequence shows grey capping running along the roof ridge and into the adjoining hip junction. The intersection photograph shows how the formed pieces meet, while another view follows the cap run across the roof. The final close view includes a gloved hand at the finished detail, providing a useful sense of its position and scale.'],
   ['Connecting the intersection to the full cap run','The intersection needs to work with the capping on both sides, not just look complete from above. The formed shapes, overlaps, visible fixing line and adjoining sheet profile all belong to that connection. This project brings those features into view. It shows the relationship between a detailed junction and the longer roof lines continuing away from it.'],
   ['Completed capping across the corrugated roof','The finished photographs show a continuous arrangement of grey hip and ridge capping against the corrugated covering. Owners can compare the wide view with the close junction detail to understand the work. Our metal roof repairs service addresses cap runs, formed intersections, fixings and adjoining sheets, with the required work planned around the actual roof layout.']
  ],services:['metal-roof-repairs','flashing-repairs']
 },
 'tile-roof-valley-chimney-flashing-repairs-perth': {
  summary:'A completed tile roof valley and chimney flashing project by Ellis Services Group, showing formed metal channels, apron edges and tile interfaces.',
  lead:'Our work on this tiled roof connects the chimney flashing with the valley below the roof junction. The completed sequence shows the formed metal, chimney apron and adjoining tile edges.',
  topics:[
   ['A tiled valley beside the chimney base','This project combines a brick chimney with a valley running through the adjoining tiled roof. The surrounding tiles and ridge area establish the roof geometry, while the grey formed metal defines the connected junctions. The photographs cover both the chimney and the valley, allowing the work to be understood as part of the same roof rather than two unrelated details.'],
   ['The formed metal details we completed','The completed work shows grey flashing around the chimney base and side, with a separate formed valley channel between the tiled slopes. The photograph sequence follows the chimney apron, the adjoining tile interface and the valley below the ridge area. These views present the roof connections our team completed and the way the metal sits within the existing tiled covering.'],
   ['Following the valley through the tile junction','A valley receives water from the roof planes on either side. Its channel therefore needs to be considered together with the adjoining tile edges and nearby roof junctions. The close photograph shows the metal continuing below the tiled ridge area, while the wider image places it beside the chimney. Both views explain the connected layout that shapes this type of repair.'],
   ['A completed chimney and valley arrangement','The finished sequence gives owners a clear view of the apron edge, side flashing, metal valley and surrounding tiles. It demonstrates the value of combining close workmanship photographs with wider roof views. For similar work, our flashing repairs and tile roof repairs services coordinate the affected metal junctions and neighbouring covering within the proposed repair scope.']
  ],services:['flashing-repairs','tile-roof-repairs','roof-leak-repairs']
 },
 'metal-roof-ridge-flashing-repair-perth': {
  summary:'Metal roof ridge flashing work by Ellis Services Group, showing a formed junction, completed ridge run and screw-fixed connections on corrugated sheets.',
  lead:'We completed the formed metal junction and ridge flashing shown on this corrugated roof. The photographs follow the finished connection, fixing line and ridge run across the adjoining roof planes.',
  topics:[
   ['A ridge junction within the metal roof covering','This corrugated roof has a formed metal connection where the roof lines meet. The project photographs show the ridge run in its wider setting and the junction from closer viewpoints. The surrounding sheets remain visible throughout the sequence, making it possible to see how the completed flashing belongs to the roof covering rather than standing apart from it.'],
   ['Our ridge flashing and connection work','The completed work shows grey formed metal along the ridge and across the adjoining junction. Close photographs show the connection, cap edges and screw-fixed line beside the corrugated sheets. Another view follows the longer ridge run. This sequence presents both the detailed workmanship at the intersection and the finished roof line extending beyond that point.'],
   ['The junction, overlap and fixing line together','A ridge connection brings formed metal, adjoining sheets and fixing positions into the same detail. Its shape changes with the roof geometry, so the intersection must connect with the continuing cap run. The photographs explain that relationship through several angles. They also show why metal roof repairs should address the connected components rather than treating a single fixing as the whole job.'],
   ['The finished ridge detail and our service scope','The completed views show the grey ridge flashing following the roof line, with its junction and nearby sheet profile clearly visible. They provide a practical example of the formed metal work we undertake. Our metal roof and flashing repair services cover ridge details, cap overlaps, affected fixing points and adjoining connections, with the repair scope organised for the property.']
  ],services:['metal-roof-repairs','flashing-repairs']
 },
 'metal-roof-fastener-repair-sequence': {
  summary:'A metal roof fastener repair sequence by Ellis Services Group, showing original roof condition, corroded fixing details, work in progress and the completed surface.',
  lead:'Our five-image metal roof repair sequence follows the job from the original roof condition through fastener work to the completed surface. It brings the affected fixing details and wider roof into one clear project story.',
  topics:[
   ['The metal roof before the fastener work','The first photograph establishes the overall roof condition before the recorded work. Close views then show corroded fastener points and a ridge-area detail. This progression matters because the fixings form part of a larger sheeted roof: their condition needs to be understood alongside the nearby covering and roof junctions, rather than viewed as an isolated spot.'],
   ['Our recorded fastener repair work','The work-stage photograph shows fastener work taking place on the metal roof. It connects the earlier condition photographs with the final overall view of the completed surface. The sequence therefore presents the affected details, the recorded work and the finished roof together. It is a practical example of our targeted metal roof repair work around fixing points.'],
   ['Why the surrounding roof remains part of the story','Fasteners secure roof components, while the sheet profile, nearby overlaps and ridge details shape their surroundings. The close photographs make the corroded fixing areas visible; the overall photographs explain where those details sit. Bringing these views together helps property owners understand the difference between a small visible component and the connected roof area that informs its repair scope.'],
   ['From site detail to the completed surface','The final photograph shows the roof surface after the recorded fastener work. Viewed alongside the installation image and earlier condition details, it completes the visual account of this job. Our metal roof repairs and roof leak repairs services provide the corresponding service paths, covering affected fixings and the adjoining roof components identified during an inspection.']
  ],services:['metal-roof-repairs','roof-leak-repairs','roof-inspection']
 },
 'roleystone-metal-roof-fastener-leak-repair': {
  summary:'Roleystone metal roof repair by Ellis Services Group, addressing affected fastener areas with structural adhesive and renewed spray coating within the agreed budget.',
  lead:'At this Roleystone property, we carried out a targeted repair around affected metal roof fastener areas. The agreed work used structural adhesive and renewed spray coating, with the scope planned around the customer’s available budget.',
  topics:[
   ['Ageing fastener areas on a Roleystone metal roof','The site record identifies ageing and rust around metal roof fastener and rivet points as part of the water-entry problem at this property. The close photographs show corrosion, aged coating and existing sealant around the affected details. These views established the condition being addressed and supported a focused discussion about the repair work and the customer’s priorities.'],
   ['A targeted scope agreed with the customer','The customer explained that the available budget was limited. We developed an economical, targeted scope around the affected fastener areas instead of presenting broader roof treatment as the only option. The agreed work followed the recorded site condition and the customer’s requirements. This approach made the included tasks clear and kept the repair focused on the areas identified for attention.'],
   ['Structural adhesive and renewed spray coating','For this property, our recorded repair used structural adhesive around affected fastener areas. We also renewed the coating by spraying as part of the customer-approved scope. These are the documented materials and work items for this job. The close photographs show the roof details that informed the repair, including the condition around fixing points and adjoining sheet surfaces.'],
   ['A defined repair with a clear service connection','The completed scope combined local fastener-area treatment with coating renewal at this Roleystone property. It demonstrates our ability to organise targeted metal roof work around the site condition and the customer’s priorities. Our metal roof repairs service addresses fixing areas and connected roof details, while roof leak repairs provides the route for investigating and repairing water-entry problems.']
  ],services:['metal-roof-repairs','roof-leak-repairs','flashing-repairs']
 },
 'wa-6121-tile-roof-valley-gutter-cleaning': {
  summary:'WA 6121 tile roof maintenance by Ellis Services Group, combining valley gutter cleaning, connected drainage clearing and tile repairs in one property scope.',
  lead:'At this Western Australia 6121 property, we combined valley gutter cleaning with tile repairs. The work addressed the connected roof drainage areas and adjoining tiled covering within one maintenance scope.',
  topics:[
   ['Accumulated material around the tiled roof drainage','The site record describes tiled roof sections, valley details and drainage routes with accumulated organic material at this Western Australia 6121, Australia property. These components were considered together when organising the job. The photographs show the tiled roof and its connected valley or drainage details, giving the cleaning work a clear position within the wider roof layout.'],
   ['Our valley gutter cleaning work','We cleaned the valley gutter areas as part of the documented roof maintenance scope. The work considered the valley and roof-edge drainage route together while clearing the relevant areas. This is an important distinction for a tiled roof: a valley receives water from adjoining slopes, and its condition belongs to the connected drainage arrangement rather than a separate isolated channel.'],
   ['Tile repairs alongside drainage maintenance','Tile repairs were completed within the agreed work for this property. Combining those repairs with the cleaning scope brought the roof covering and drainage details into the same job. The site photographs help explain the adjoining tiles and valley arrangement, while the recorded work identifies the two main tasks: clearing the relevant drainage areas and repairing the affected tiled covering.'],
   ['One coordinated roof maintenance scope','The completed job brought valley gutter cleaning and tile repairs together at the WA 6121 property. It provides an example of the maintenance and targeted repair work our team coordinates on tiled roofs. Our roof maintenance, gutter repairs and tile roof repairs services offer the corresponding pathways for owners who need drainage upkeep and covering repairs planned together.']
  ],services:['roof-maintenance','gutter-repairs','tile-roof-repairs','roof-inspection']
 }
};
