// Editorial data for the approved October content revision. Existing URLs stay stable.
export const revisedGuides = {
 'roof-leak-detection-perth': {
  title:'Roof Leak Detection Perth: Tracing Recurring Leaks After Rain',service:'roof-leak-repairs',project:'roleystone-metal-roof-fastener-leak-repair',
  description:'Learn how ceiling stains, rain patterns and roof junctions guide leak detection in Perth, and how identified defects are repaired.',
  intro:'A recurring roof leak needs its water path traced, not another patch chosen from the ceiling stain alone. Ellis Services Group investigates the roof covering, junctions and drainage above the affected area and repairs the components responsible for water entry. This guide explains how the evidence fits together and why a previous repair can leave a leak unresolved.',
  sections:[
   ['Why the ceiling stain can be away from the entry point','Water can move along under-roof layers or building members before reaching a ceiling. A stain identifies the affected room, but the roof directly above it is only part of the investigation. We relate the indoor position to the roof slopes, valleys, walls and penetrations nearby.','Our team checks adjoining tiles or sheets as well as the reported area. This helps distinguish an entry defect from the route water follows after entering. Existing interior photographs support that investigation without requiring the owner to enter the roof space.'],
   ['Leaks during heavy rain and wind-driven rain','A downpour increases flow through valleys, gutter outlets and downpipes. An obstruction or damaged drainage connection can allow water to back up while the roof covering appears intact. We inspect the connected drainage route alongside laps and flashings.','Wind-driven rain can expose a weak overlap or junction differently from calm rain. Tell us which weather events trigger the leak and whether dripping begins immediately or later. We use that history to focus inspection, then specify work from the physical defects found.'],
   ['Investigating a leak that returns after repair','A previous patch can leave adjoining corrosion, a deteriorated fixing or a poorly connected flashing untreated. We review the repair area and inspect beyond its edges rather than assuming the same surface needs more sealant.','The repair can involve replacing a damaged tile, compatible fastener work, renewing an affected flashing or restoring drainage. The important distinction is between closing the entry defect and simply covering an indoor symptom. The proposed scope identifies the roof components to be repaired.'],
   ['From leak investigation to a defined repair scope','Our assessment brings together the affected rooms, rain history, covering material, previous work and accessible roof details. We explain the identified defects, materials and access arrangements before the agreed repairs begin.','Completion checks focus on the repaired connections, adjoining covering and connected drainage. The checks appropriate to the job are agreed with the scope; photographs and records help explain the work completed. Our metal fastener leak-repair case shows the roof condition, fixing details and completed work in a photographed repair sequence.']
  ],questions:[['Do I need to wait for another storm before contacting you?','No. Existing water marks, photographs and the timing of previous leaks help us prepare an inspection. Keep clear of wet roof access and report active dripping when you contact our team.'],['Can you investigate a leak after someone has already repaired it?','We inspect the previous repair and its adjoining roof components, explain the remaining defects and prepare the repair work needed for the current condition.']]
 },
 'tile-roof-repairs-perth-guide': {
  title:'Broken Roof Tiles in Perth: Replacement, Matching and Leak Repairs',service:'tile-roof-repairs',project:'tile-roof-valley-chimney-flashing-repairs-perth',
  description:'Broken or displaced roof tiles need compatible replacements and checks of adjoining ridges, valleys and flashings. Explore the repair process.',
  intro:'A tiled roof repair restores the damaged tile and the roof connections around it. Ellis Services Group repairs concrete and terracotta roofs in Perth, inspecting cracked, displaced and missing tiles alongside ridge caps, valleys and flashings. Matching the tile profile and maintaining the overlapping roof detail are central to the work.',
  sections:[
   ['Cracked tiles, slipped tiles and exposed gaps','Cracked tile faces and edges, displaced tiles and missing pieces create different repair requirements. We inspect the affected area and nearby tiles to identify the damage and determine which pieces need replacement or repositioning.','Water entry can also involve a valley or flashing beside otherwise serviceable tiles. We check those interfaces when a broken tile is found near a reported leak, so the repair addresses the connected problem rather than stopping at the most visible damage.'],
   ['Matching concrete and terracotta tile profiles','Tile shape, overlap and fit matter more than a colour-only match. A replacement needs to sit correctly with adjoining tiles and suit the existing roof detail. Our team checks the material and profile before selecting compatible replacements.','Older roofs can require attention to the available tile profile and surrounding condition. We explain the replacement arrangement as part of the scope, including any related tile edges or junctions that need work. We do not treat every concrete or terracotta tile as interchangeable.'],
   ['Checking ridge caps and tile-to-flashing connections','Field tiles sit beside bedding, ridge caps and formed metal details. Loose capping or a damaged flashing can affect the same area as a cracked tile. We inspect those connections before setting the full repair extent.','At a chimney or valley, the tile edge and flashing form a water-shedding connection. Our valley and chimney project shows these components together. Such photographs illustrate the relevant roof details; the condition of your own roof determines which parts we repair.'],
   ['Replacing damaged tiles and reviewing the finished area','The agreed work identifies replacement tiles, adjoining components, safe access and any ridge or flashing repairs. Our team restores the affected covering without describing a new surface coating as a substitute for broken-tile replacement.','After the repair, we review tile seating, overlaps and the adjoining roof detail included in the job. Customers can ask for the scope and completed-work record so the distinction between tile replacement, ridge work and flashing work is clear.']
  ],questions:[['Does one broken tile explain every roof leak?','A damaged tile is a repair item, but water can also enter at adjoining ridges, valleys or flashings. We inspect those connections when tracing the leak.'],['Should I move the tiles before the inspection?','Leave roof-level access and tile handling to our team. Ground-level photographs and the location of indoor water marks are useful preparation without disturbing the covering.']]
 },
 'metal-roof-repairs-perth-guide': {
  title:'Metal Roof Screws and Washers: Leak Causes and Repairs in Perth',service:'metal-roof-repairs',project:'metal-roof-fastener-repair-sequence',
  description:'Explore leaking roof screws, worn washers and corrosion around fixing points, with a photographed Perth metal-roof fastener repair sequence.',
  intro:'Metal roof fasteners do more than hold sheets in place: exposed fixing points also need effective sealing. Weathered washers, corroded screw heads and damaged metal around holes require different repairs. Ellis Services Group checks the fixing and the sheet together before selecting compatible materials and completing the agreed work.',
  sections:[
   ['How a roof screw and sealing washer work together','A sealing washer closes the exposed connection between the fastener and the roof sheet. Wear, poor seating or damage can compromise that connection. We inspect the screw head, washer and surrounding sheet instead of judging the fixing by its appearance alone.','A loose or corroded fixing needs attention to its holding point as well as its seal. Simply tightening a screw is not a universal repair. The work must suit the existing metal, sheet profile and condition at the fixing location.'],
   ['Corrosion at the fastener and around the fixing hole','Rust on a screw and corrosion in the sheet around it are separate conditions. A new fixing does not restore metal that has lost its integrity. Our inspection establishes whether the area supports fastener replacement or needs sheet or connection work as well.','Where the surrounding material remains serviceable, local compatible fastener replacement can form part of a targeted repair. More extensive sheet deterioration needs a different scope. We explain the affected areas and proposed materials before work begins.'],
   ['Sheet laps, ridge caps and penetrations near the leak','A leak close to a fixing line can originate from an adjoining lap or formed flashing. We check the route water takes across the roof, including ridge and hip capping, wall connections and penetrations relevant to the reported area.','This broader check prevents a screw-only scope from overlooking an adjoining defect. The agreed repair can combine fixing work with local sheet, capping or flashing repairs where inspection identifies connected damage.'],
   ['What our fastener repair photographs demonstrate','The linked project sequence shows the roof before work, close corroded fixing details, the work stage and the completed surface. It gives customers a concrete view of the components involved in fastener repairs rather than relying on a generic roof photograph.','For a new property we inspect the actual fixings, sheet condition and access. The scope identifies which components need work and how the finished connections will be reviewed. The photographs are evidence of that particular sequence, not a promise that every metal roof needs the same work.']
  ],questions:[['Can local fastener work avoid replacing the whole roof?','Local repairs suit defects where the surrounding sheets remain serviceable. Our inspection distinguishes isolated fixing damage from deterioration that needs broader component replacement.'],['Are tin, corrugated and COLORBOND roof fixings interchangeable?','The existing profile, coating and material guide the repair. We select compatible fixings and inspect the adjoining sheet rather than using a single arrangement for every roof.']]
 },
 'ridge-capping-repairs-perth-guide': {
  title:'Roof Repointing vs Rebedding: Choosing Ridge Repairs in Perth',service:'ridge-capping-repointing',project:'tile-roof-valley-chimney-flashing-repairs-perth',
  description:'Understand repointing, rebedding and loose ridge caps, including how cap stability and adjoining tiles guide tiled-roof repair work.',
  intro:'Repointing renews the outer pointing around ridge caps; rebedding restores the supporting bedding beneath them. These are related but distinct roof repair tasks. Ellis Services Group checks ridge and hip runs, cap stability and adjoining tiles before recommending the work required for a Perth tiled roof.',
  sections:[
   ['Pointing and bedding have different roles','Bedding supports the ridge caps, while the outer pointing finishes the exposed joins. Deterioration in one layer does not automatically establish the condition of the other. Our team checks both the visible finish and cap stability.','This distinction matters when quoting. A scope described only as ridge repair can leave the intended work unclear. We explain whether the job addresses pointing, bedding, caps or adjoining tiles, and identify the affected runs.'],
   ['When repointing is the relevant repair','Caps that remain securely supported can require renewal of deteriorated pointing. We assess the underlying support and tile connections before specifying a pointing-only scope, rather than treating every visible mortar crack in the same way.','Preparation and the pointing material must suit the existing detail. The scope includes the sections needing work and the condition of adjoining caps and tiles. It should not present a surface finish as the solution to unstable caps.'],
   ['When loose caps need bedding work','Loose caps or deteriorated supporting bedding require attention to that support. Our team checks the extent along the ridge or hip and explains the bedding and cap work included in the proposed repair.','Nearby damaged tile edges or connected junctions can need repair at the same time. We coordinate these work items so the repaired cap run fits into the adjoining covering rather than leaving a disconnected weak point.'],
   ['Ridges, valleys and roof junctions as connected details','Our tiled-roof service photographs show ridge details alongside valleys and chimney connections. The linked valley and chimney case illustrates adjoining tiled-roof junctions; it is not presented as a rebedding case.','For ridge work at your property, we define the runs, material, access and completion checks after inspection. The finished scope should make clear what was renewed and which surrounding details were addressed, so future maintenance has a useful record.']
  ],questions:[['Is repointing enough when ridge caps are loose?','Loose caps require their supporting bedding and connections checked. We repair the support where needed rather than renewing only the visible pointing.'],['Can you repair adjoining broken tiles during ridge work?','We include affected caps, bedding, pointing and adjoining tiles in the scope where inspection identifies connected defects.']]
 },
 'roof-valleys-flashing-repairs-perth': {
  title:'Roof Valley and Chimney Flashing Leaks: Repair Methods in Perth',service:'flashing-repairs',project:'tile-roof-chimney-flashing-repair-perth',
  description:'Learn how valleys and chimney flashings manage rainwater, what defects need repair, and how formed metal connects with tiled roofs.',
  intro:'Valleys collect water from adjoining slopes, while flashings protect junctions such as chimneys and walls. Ellis Services Group repairs and replaces these roof details in Perth, checking the formed metal together with adjoining tiles or sheets and the drainage route below. The work restores the connection, not just the appearance of a metal strip.',
  sections:[
   ['Roof valleys carry concentrated runoff','A valley receives water from more than one roof face. Debris, corrosion and damage near its outlet can interrupt that route. We inspect the channel and the roof covering along its edges when investigating water entry.','Clearing debris and repairing deteriorated metal are different tasks. An unobstructed channel can still need component repair, while otherwise serviceable material can need maintenance. We specify the work from the condition of the valley and adjoining roof.'],
   ['Chimney flashing joins masonry with the roof covering','A chimney creates a junction between brickwork and sloping roofing. Formed flashings need to connect with both surfaces and guide water onto the roof covering. We inspect the chimney base, exposed connections and surrounding tile or sheet edges.','The linked chimney project shows finished metal details at the brick base and the adjacent valley. It helps explain the components in a chimney flashing repair. Your scope sets out the particular connections and materials that need work after inspection.'],
   ['Why a sealant patch is not every flashing repair','Sealant can be part of an appropriate connection, but it does not replace damaged metal or correct a disconnected water-shedding detail by itself. We inspect previous patches and the formed material around them before choosing the repair.','Work can involve local connection repair or replacement of the affected flashing. The adjoining covering, material compatibility and direction of runoff are included in that decision, so the new detail works with the roof rather than as an isolated patch.'],
   ['Connecting the repaired junction with its drainage outlet','Water leaving a valley or roof junction must continue into a functioning drainage route. We check connected gutters and outlets where they relate to the affected area and identify any additional repair or clearing work.','The agreed scope explains the flashing or valley components, adjoining roof work and access. Our team reviews the finished connections within that scope. Customers with recurring leaks should include previous repair details and the timing of water entry when arranging inspection.']
  ],questions:[['Can chimney flashing repairs be combined with valley work?','We inspect the connected tiled or metal roof junction and coordinate both work items when the defects involve the chimney and valley.'],['Does debris in a valley mean the metal needs replacing?','Debris calls for a drainage condition check. We distinguish clearing from repairs to corroded or damaged valley material and explain which work is required.']]
 },
 'roof-inspection-perth-guide': {
  title:'What a Roof Inspection Checks Before Perth Winter Rain',service:'roof-inspection',project:'wa-6121-tile-roof-valley-gutter-cleaning',
  description:'A practical roof inspection checklist covering tiles, metal fixings, ridge caps, flashings and drainage, with clear repair priorities for Perth homes.',
  intro:'A roof inspection identifies the covering and drainage defects that need attention before repairs or maintenance are arranged. Ellis Services Group inspects Perth tiled and metal roofs, explains the findings and organises the work appropriate to the property. Inspection identifies the problem; maintenance and repair address it.',
  sections:[
   ['Inspecting tiles and metal sheets before wet weather','We look for cracked, missing or displaced tiles and examine adjoining ridge and junction details. On metal roofs, inspection includes sheet condition, exposed fixings, laps and formed capping relevant to the property.','Roof age alone does not define the repair scope. The actual material condition and the extent of local damage determine whether work involves isolated replacement, connection repairs or a broader component scope.'],
   ['Checking ridge, wall and penetration connections','Ridge and hip capping, roof-to-wall flashings and penetrations join different roof surfaces or materials. We inspect their stability and connections alongside the reported leak area or maintenance concern.','Chimneys, vents and other openings need attention to the adjoining covering as well as the flashing itself. The findings should identify the affected components and the work needed, rather than listing a vague roofline concern.'],
   ['Following drainage through valleys, gutters and downpipes','Leaves and deposits can restrict channels and outlets, while corroded material or disconnected joints require repairs. We inspect the water route and distinguish clearing tasks from damaged components.','Our valley and gutter cleaning project illustrates maintenance linked with local tile work. It provides a useful example of related work items; it does not establish a fixed maintenance interval or a universal checklist for every building.'],
   ['Turning inspection findings into repair priorities','We explain the defects found, affected areas and recommended sequence of work. The proposed scope identifies materials, access and included tasks so customers can distinguish urgent repairs from maintenance that can be planned.','Before the visit, provide the suburb, roof material if known, leak history and existing photographs. Keep roof access to our team. After inspection, ask which items need repair, how those repairs connect with drainage and what completed-work records are included.']
  ],questions:[['Is inspection the same service as ongoing roof maintenance?','Inspection identifies roof condition and priorities. Maintenance includes the agreed clearing, upkeep and local repairs that follow those findings; the scope distinguishes each task.'],['What will the proposed roof repair scope explain?','It identifies affected components, recommended work, materials, access and included tasks. Our team explains repair priorities and separates them from future maintenance items.']]
 }
};

export const serviceEditorial = {
 'roof-repairs':{heading:'Tile and metal roof repairs — the work we carry out',paragraphs:['Ellis Services Group repairs damaged roof coverings and the connections that keep rain outside. Our Perth team replaces broken tiles, repairs metal fixings and sheets, restores ridge caps and renews affected valleys and flashings. We inspect adjoining components so the work addresses the roof system around the defect.','The repair scope identifies the components, materials and access needed for your property. Local repairs address isolated damage where surrounding roofing remains serviceable; wider component work is arranged when inspection identifies more extensive deterioration. Leak investigation and drainage repairs are coordinated with the covering work where they are connected.'],cards:[['Covering repairs','We replace damaged tiles and address affected metal sheets, screws and washers with compatible materials.'],['Ridge and junction work','We repair unstable ridge details and damaged valleys or flashings at walls, chimneys and penetrations.'],['Connected drainage','We inspect gutter outlets and downpipes related to the repair area and include the necessary clearing or component repairs.']]},
 'roof-leak-repairs':{heading:'Tracing water entry and repairing the connected roof defects',paragraphs:['Ceiling stains, intermittent dripping and water returning after rain are reasons to arrange a roof leak investigation. We relate indoor evidence to the roof covering, nearby junctions and drainage route. The inspection includes the affected tiles or sheets, fixing points, valleys and flashings rather than assuming the stain marks the entry point.','Our team repairs the defects identified in that investigation. Work can include tile replacement, compatible fastener repairs, local sheet work, flashing renewal and connected drainage repairs. We explain the cause established by inspection, the included work and appropriate completion checks before arranging the repairs.'],cards:[['Ceiling stains and dripping','We connect the affected room with the roof slopes, penetrations and water paths above it.'],['Heavy-rain and recurring leaks','We inspect drainage restrictions, previous patches and nearby junctions that can admit water during particular rain conditions.'],['Repairing the entry defect','We repair the identified covering, fixing or flashing component and review the adjoining water route.']]},
 'tile-roof-repairs':{heading:'Replacing damaged tiles and restoring adjoining roof details',paragraphs:['We repair concrete and terracotta tile roofs across Perth. Cracked, broken, displaced and missing tiles are checked with the surrounding covering so replacement pieces fit the roof profile and overlapping arrangement. Our scope identifies the tiles and local roof areas needing work.','Where tile damage connects with loose ridge caps, a valley or chimney flashing, our team coordinates the adjoining repairs. We check tile seating and the finished interfaces within the agreed scope. This restores the damaged roof detail rather than covering it with a cosmetic finish.'],cards:[['Tile profile and fit','Replacement selection considers the existing concrete or terracotta profile and the adjoining overlaps.'],['Ridge and hip edges','We assess damaged cap connections, bedding and neighbouring tile edges when setting the repair scope.'],['Valley and flashing interfaces','We restore local tile connections beside valleys, chimneys and walls where inspection identifies defects.']]},
 'metal-roof-repairs':{heading:'Metal sheet, fastener and flashing repairs matched to your roof',paragraphs:['Our metal roof repairs cover corrugated, tin and COLORBOND-style roofing, including screws, sealing washers, sheet laps, ridge and hip capping and formed flashings. We inspect the sheet beneath each affected connection and assess corrosion before selecting the local repair or replacement work.','A new fixing does not restore a weakened sheet, and a surface coating does not repair a damaged junction. We distinguish fastener defects, sheet damage and flashing failures, then coordinate the required components. The scope identifies compatible materials, access and the connections to be reviewed on completion.'],cards:[['Fasteners and washers','We inspect the head, sealing washer and sheet around the fixing before carrying out compatible replacement work.'],['Sheet laps and corrosion','We assess local damage and adjoining sheet integrity to define the extent of sheet or connection repairs.'],['Capping and penetrations','We repair formed ridge, hip and flashing details together with the roof material around them.']]},
 'ridge-capping-repointing':{heading:'Repointing, rebedding and repairs to ridge and hip caps',paragraphs:['We inspect ridge cap stability, the supporting bedding and outer pointing as separate parts of the repair. Secure caps with deteriorated pointing require different work from loose caps with failed support. Our team explains which ridge or hip runs need repointing, bedding repairs or replacement caps.','The scope also covers damaged neighbouring tiles where they affect the repaired ridge detail. We restore the affected support and finish, then review cap seating and the adjoining covering. This gives customers a clear description of the work rather than using repointing and rebedding as interchangeable labels.']},
 'flashing-repairs':{heading:'Repairing valleys and formed flashings at roof junctions',paragraphs:['We repair and replace formed metal details where roof surfaces meet walls, chimneys, skylights and penetrations. Valley channels are inspected with the adjoining tiles or sheets and the drainage outlet. Our scope identifies damaged material, disconnected edges and junctions requiring repair.','The work restores water-shedding connections suited to the existing roof. We assess previous patches, select compatible material and repair adjoining covering details as needed. Connected gutters and outlets are checked where they affect the repaired valley or flashing route.']},
 'storm-damage-roof-repairs':{heading:'Urgent roof damage assessment, protection and planned repairs',paragraphs:['Storm damage can leave displaced tiles, loose capping, affected metal sheets or damaged drainage connections. Our team establishes the affected areas and access requirements, then arranges the protection and repairs appropriate to the condition found. Report active water entry and the location of damaged roof components when contacting us.','Urgent enquiries are prioritised; attendance is arranged promptly when weather, site access and safety conditions allow. Temporary protection and permanent repairs are distinct work items. We explain the immediate measures and the subsequent covering, flashing or drainage work needed for the property.'],cards:[['Active leaks and displaced covering','We prioritise reported water entry and inspect damaged tiles or sheets when safe access is available.'],['Protection and repair sequence','We arrange appropriate protection and identify the permanent components needing repair or replacement.'],['Site and access coordination','We plan access around weather and safe work conditions and keep the property contact informed about the next step.']]},
 'roof-inspection':{heading:'A roof condition inspection with clear repair priorities',paragraphs:['Our inspection covers the accessible covering, ridge and hip details, valleys, flashings, penetrations and drainage relevant to your property. We relate reported leaks to the roof above and identify damaged components rather than relying on an indoor mark alone.','We explain the findings and the recommended work, including the affected area, proposed materials and access. Inspection identifies condition and priorities; repair and maintenance are arranged as defined work items. This separates the assessment from the tasks required to address its findings.']},
 'roof-maintenance':{heading:'Planned upkeep for roof coverings and drainage',paragraphs:['Roof maintenance combines condition checks, clearing of affected drainage routes and local repairs. We inspect tiles or metal sheets, exposed fixings, ridge details and flashings and address the work included in the maintenance scope. Debris clearing does not replace repairs to damaged components.','Tree cover, roof form, material and exposure influence the priorities at each property. We explain which areas need immediate work and which can be monitored through planned maintenance. The scope connects roof upkeep with valley channels, gutter outlets and downpipes.']},
 'gutters-downpipes':{heading:'Restoring the connected drainage route from roof edge to discharge',paragraphs:['We inspect gutters, outlets and downpipes as a connected system. Overflow at the roof edge can involve debris, alignment, damaged joins or a restriction downstream. Our team identifies the affected route and distinguishes cleaning from component repair.','The work can combine clearing, support adjustment, local gutter replacement and repairs to downpipe connections. We explain the included roof drainage components and reconnect the affected route. The dedicated gutter and downpipe services describe those repair tasks in more detail.']},
 'gutter-repairs':{heading:'Gutter joint, support and local section repairs',paragraphs:['We repair leaking gutter joints, sagging runs, loose brackets, corroded sections and outlet connections. Inspection checks the material beside the defect and the connected downpipe so the scope addresses both the damaged gutter and its drainage route.','A sound joint and a corroded gutter section need different work. We identify where joint repair, support adjustment or local section replacement is required and use compatible connections. Completion review includes the repaired run, supports and outlets included in the job.']},
 'downpipe-repairs':{heading:'Repairing downpipe joints, supports and damaged pipe sections',paragraphs:['We restore leaking or disconnected downpipe joints, damaged pipe sections and loose supports. The inspection follows the connection from the gutter outlet down the visible pipe route and identifies the components needing repair or replacement.','Our team secures the affected connections and brackets and explains the included discharge arrangement. Where the problem also involves the gutter outlet, we coordinate both work items. The scope distinguishes visible roof drainage repairs from separate underground drainage work.']},
 'roof-cleaning-painting':{heading:'Roof cleaning and painting — repair, preparation and finish',paragraphs:['Cleaning removes deposits from suitable roof surfaces and drainage areas; painting involves a prepared substrate and a compatible coating system. We inspect the existing tile or metal finish, identify local defects and specify the cleaning work separately from coating preparation.','Broken tiles, deteriorated fixings and damaged flashings need repair before finishing. Our team explains the preparation, surface work and adjoining drainage protection for the job. Coating product selection and application requirements follow the actual substrate and the agreed scope, not a single package for every roof.']},
 'commercial-roof-repairs':{heading:'Roof and drainage repairs coordinated around building operations',paragraphs:['We repair roofing for Perth businesses and managed properties, including sheet connections, flashings, penetrations, gutters and drainage outlets. The inspection identifies the affected roof areas and relates reported indoor leaks to the covering and equipment connections above.','Our team coordinates the site contact, access and proposed sequence with the building manager. Work can be staged around operating requirements where the scope supports that arrangement. We explain the affected components, materials and included tasks so tenants and managers understand the repair plan.']}
};

export const faqGroups=[
 ['Leaks and urgent repairs',[
  ['How do you find the source of a roof leak?','We connect the indoor stain or drip with the roof covering, junctions and drainage above it, then repair the defects identified in the investigation.','roof-leak-repairs'],
  ['Can you investigate a leak that only happens in heavy rain?','We inspect valleys, outlets, roof laps and flashings and use the rain history to focus the investigation. Repairs follow the actual defects found.','roof-leak-repairs'],
  ['Can a ceiling mark help you prepare for inspection?','The room location and timing of water entry help us relate the symptom to the roof above. Existing photographs are useful; keep roof access to our team.','roof-leak-repairs'],
  ['What happens when I report urgent storm damage?','Urgent enquiries are prioritised; attendance is arranged promptly when weather, site access and safety conditions allow. We identify the protection and permanent repairs needed.','storm-damage-roof-repairs'],
  ['Can you check a roof that has already been patched?','We inspect the previous work and adjoining roof details to identify remaining defects and specify the repairs required for the current condition.','roof-leak-repairs']
 ]],
 ['Tiles, metal roofing and roof junctions',[
  ['Which roof materials do you repair?','Our services cover concrete and terracotta tiles and metal roof sheets, with connected ridge, valley and flashing work. The existing profile and condition guide the materials used.','roof-repairs'],
  ['How do you repair broken or displaced tiles?','We inspect the damaged tiles and adjoining roof, select compatible replacements or repositioning work and restore the affected covering.','tile-roof-repairs'],
  ['Can leaking screws or washers be repaired on a metal roof?','We inspect the fixing, washer and surrounding sheet and carry out compatible fastener work or local sheet repair where needed.','metal-roof-repairs'],
  ['What is the difference between repointing and rebedding?','Ridge capping covers the junction between roof planes. Repointing renews the outer pointing around caps; rebedding restores the supporting bedding. We check cap stability to specify the appropriate work.','ridge-capping-repointing'],
  ['What does roof flashing do?','Flashing directs water away from roof-to-wall junctions, chimneys and penetrations. We repair damaged connections and replace affected formed metal where required.','flashing-repairs'],
  ['Can you repair valleys and chimney flashings together?','We inspect the connected junction and coordinate repairs to the valley, chimney flashing and adjoining tiles or sheets where the defects are related.','flashing-repairs'],
  ['Why do roof edges need checking during a repair?','Roof edges connect the covering with flashings, fascia and drainage. We check adjoining damage and drainage connections when they affect the repair area.','roof-repairs']
 ]],
 ['Gutters, downpipes and maintenance',[
  ['Does gutter overflow always mean the gutter needs replacing?','We distinguish debris or an outlet restriction from damaged joints, support problems and corrosion. The scope identifies cleaning, adjustment or replacement work.','gutter-repairs'],
  ['Do you repair downpipe joints and brackets?','We repair affected joints, supports, pipe sections and gutter outlet connections along the visible drainage route.','downpipe-repairs'],
  ['Can gutters and downpipes be handled as one job?','We inspect the connected water route and coordinate the required clearing and component repairs in one scope where appropriate.','gutters-downpipes'],
  ['What does roof maintenance include?','Maintenance includes the agreed condition checks, drainage clearing and local repairs to tiles, fixings, ridges and flashings. We set priorities from the property condition.','roof-maintenance'],
  ['Can you inspect the roof before winter rain?','We inspect the covering, junctions and drainage, explain identified defects and organise repair and maintenance priorities before wet weather.','roof-inspection'],
  ['Is cleaning the same as painting or restoration?','Cleaning, coating preparation and repairs are different tasks. We specify surface work for the tile or metal material and address damaged components before a finish is applied.','roof-cleaning-painting']
 ]],
 ['Inspection, quotes and arranging the work',[
  ['What should I send before a roof inspection?','Send the suburb, roof material if known, affected area, leak timing, previous repair details and existing photographs. Our team uses them to prepare the visit.','roof-inspection'],
  ['Do I need to climb onto the roof for photographs?','No. Photographs are optional and do not replace an on-site assessment. Use existing images or photographs from a safe ground-level position only. Our team arranges the roof inspection and access required for the work.','roof-inspection'],
  ['What should a roof repair quote explain?','The scope should identify the affected components, proposed work and materials, access arrangements and included tasks. Ask our team about any item needing clarification.','roof-repairs'],
  ['How do you choose between repair and component replacement?','We assess the extent of damage and condition of surrounding material. Local defects can suit targeted repairs; deteriorated components can require replacement.','repair-options'],
  ['Do you work on commercial and managed buildings?','We coordinate inspection and repairs with the building manager, including site access, affected tenancies and operating requirements relevant to the work.','commercial-roof-repairs'],
  ['Can I compare an affected area with a nearby roof section?','Existing photographs of both areas can help explain what changed. We inspect the actual material and connections before specifying the repair.','roof-inspection']
 ]],
 ['Our work and company details',[
  ['Where can I see your roof repair projects?','Our project library includes supplied photographs of metal fasteners, ridge capping, chimney flashing and tiled-roof drainage work, linked to the relevant services.','gallery'],
  ['Are the completed-work photographs your supplied project images?','Pages labelled as completed work or project sequences use the supplied site photographs. General guide imagery illustrates roof materials and components; it is not evidence of a job at your property.','gallery'],
  ['Where can I read about roof materials and repair methods?','Our guides explain leaks, tile and metal repairs, valleys, flashings and maintenance, with links to the team that carries out the work.','news'],
  ['Who operates Perth Roof Care?','Perth Roof Care is operated by Ellis Services Group Pty Ltd. Our Perth office is at 140 St Georges Terrace, Perth WA 6000.','about'],
  ['How do I arrange a repair?','Call 0405 878 406, email ellisservicesgroup3@outlook.com or send the contact form with your property and roof details.','contact'],
  ['How is information sent through the website handled?','The privacy page explains the website contact channels and enquiry information. Contact our team if you have a question about the details you submit.','privacy']
 ]]
];
