// Answers are ordered to match the three service questions generated by build.mjs.
export const serviceAnswers = {
  'roof-repairs': [
    'A ceiling leak belongs with our roof leak investigation service; damaged tiles with tile repairs; and sheet, screw or washer defects with metal roof repairs. Where more than one component is involved, our roof repair team checks the connected ridge, valley, flashing and drainage route and coordinates the work in one scope.',
    'A useful roof repair quote identifies the affected roof area, the defects found, proposed repairs, materials, access arrangements and what is included in the price. We explain the repair priorities and distinguish local component replacement from wider roof work so you can understand what you are commissioning.',
    'Targeted repair suits isolated defects where the surrounding roof remains serviceable, such as a broken tile, failed fixing or damaged flashing. Wider restoration addresses a broader combination of repairs and surface condition. We inspect the roof first and recommend the extent of work that addresses its actual condition.'
  ],
  'roof-leak-repairs': [
    'Heavy rain increases the amount of water passing through valleys and gutters, while wind can drive rain towards laps and junctions. An overflowing outlet, damaged tile, deteriorated fixing or flashing defect can then admit water. We connect the rainfall pattern and indoor stain with the roof above, inspect the water route and repair the identified defects.',
    'Yes. A recurring leak can originate at a valley, chimney flashing, roof-to-wall junction or penetration and travel before it becomes visible indoors. We inspect the junction together with the adjoining roof covering, laps and drainage outlet, then repair or replace the affected component and check the connected water path.',
    'Our assessment brings together the location of stains or drips, the weather pattern, roof material, repair history and accessible roof details. We inspect tiles or sheets, ridges, flashings, penetrations and drainage around the affected area, then explain the identified defects and proposed repair work.'
  ],
  'tile-roof-repairs': [
    'Yes. We replace individual damaged concrete or terracotta tiles when compatible replacements can be sourced and the surrounding roof is suitable for a local repair. We check the tile profile, adjoining overlaps and support beneath the affected area, fit the replacement and restore the tile alignment.',
    'When damage lies beside a ridge, valley or chimney, repairing the tile alone can leave the adjoining defect untreated. We inspect ridge bedding and pointing, valley drainage and flashing connections as part of that repair area, and include the connected work required to restore the roof detail.',
    'Send the suburb, roof material if known, the position of broken or displaced tiles and any indoor water marks. Ground-level photographs of the whole affected roof face and closer photographs already available help us plan access and compatible tile repairs. Our team carries out the roof inspection and repair work.'
  ],
  'metal-roof-repairs': [
    'Yes. Deteriorated sealing washers, corroded screw heads or loose fixings can compromise the fixing point. We inspect the fasteners alongside the sheet condition and select compatible replacements for the roof material. Correct seating and the condition around each fixing are part of the repair.',
    'Ridge and hip capping protect transitions between roof planes, while flashings protect walls, edges and penetrations. Loose fixings, damaged laps or deteriorated junctions can require capping or flashing repairs. We inspect the adjoining sheet profile and water path and fit the repair detail to that roof.',
    'Yes, where the surrounding sheets remain serviceable. Local work can include compatible fastener replacement, flashing repairs or replacement of affected sheets. We check the extent of corrosion and damage before recommending a local scope or wider sheet replacement.'
  ],
  'ridge-capping-repointing': [
    'Repointing renews the outer pointing finish along ridge caps; rebedding renews the supporting bedding beneath them. Firm caps with deteriorated pointing can require repointing, while loose caps or failed bedding need the supporting detail repaired as well. We inspect stability before recommending the correct work.',
    'The quote should identify the ridge or hip runs, whether repointing or rebedding is required, damaged caps or adjoining tiles, the materials and access arrangements. We describe how the caps will be secured and which connected roof details are included in the repair.',
    'A ridge defect should be checked with surrounding tiles when there are loose caps, cracked tile edges, disturbed bedding or nearby water marks. We inspect the ridge-to-tile connection and repair the affected caps, pointing, bedding and adjoining tiles as required.'
  ],
  'flashing-repairs': [
    'Roof flashing directs water across changes in roof shape and around walls, chimneys, skylights and penetrations. Its shape, overlaps, fixings and material compatibility all matter. We repair or replace damaged flashing and connect the new detail to the surrounding roof and drainage route.',
    'Debris in an otherwise serviceable valley calls for clearing and inspection. Local damage can require a defined repair, while perforation, extensive corrosion or an unsuitable valley detail can require replacement. We check the valley material, tile or sheet edges and outlet before specifying the work.',
    'Water near a skylight can enter through the skylight flashing, adjoining tiles or sheets, or a higher junction. We inspect the opening, surrounding laps and uphill water path together, then repair the identified roof or flashing defect rather than treating only the indoor stain.'
  ],
  'gutter-repairs': [
    'Tell us which side of the property is affected, where water escapes and whether the gutter is sagging, leaking at a join or corroded. We check the gutter fall, supports, seams and outlets, then repair the joints, brackets or affected lengths needed to restore drainage.',
    'Yes. Water from a valley outlet or roof edge can concentrate at one gutter section. We inspect how that roof detail discharges into the gutter, check the outlet and downpipe and include the connected roof-edge repairs where required.',
    'Useful details include the location of the outlet, leaks at the connection, loose brackets and where the downpipe carries water. We check the gutter outlet, pipe joints and supports together and repair the affected roofline drainage connection.'
  ],
  'gutters-downpipes': [
    'No. Debris is one cause, but poor fall, a restricted outlet, damaged guttering or a blocked or disconnected downpipe can also cause overflow. Our team checks the whole visible route, clears deposits where needed and repairs the component responsible for the drainage problem.',
    'Check both when overflow occurs near an outlet, water escapes from a pipe joint or the gutter remains full after rain. We inspect the connection between gutter and downpipe, pipe supports and the visible discharge route so the repair addresses the connected drainage system.',
    'A ground-level overview of the affected roof edge, a photograph of the outlet and downpipe and any existing image of water escaping are useful. Tell us the rain conditions and which side of the property is affected. We arrange the roof-access inspection and carry out the drainage work.'
  ],
  'downpipe-repairs': [
    'Yes. Loose brackets allow pipe movement, which can strain joints and the gutter outlet connection. We check the support spacing, wall fixings and pipe condition, then secure or replace the affected supports and repair damaged joints.',
    'Water spilling over the gutter edge points us towards collection and outlet performance; water escaping from a pipe seam or disconnected section identifies a downpipe detail to inspect. We check both adjoining components and explain which repair is required.',
    'Use our combined gutters and downpipes service when the problem includes gutter overflow, a restricted outlet and pipe defects, or when the affected component is unclear. We inspect the connected roof-edge drainage route and organise the necessary cleaning and repairs.'
  ],
  'roof-maintenance': [
    'Provide the roof material, approximate age if known, previous repairs, nearby trees and any recurring leaks or drainage problems. We inspect the roof covering, ridges, flashings, valleys and gutters and prioritise maintenance according to their condition.',
    'Before seasonal rain, have debris cleared from roof drainage routes and damaged tiles, deteriorated fixings and flashing defects inspected. Our team checks outlets and connected downpipes, carries out necessary repairs and identifies areas that need follow-up maintenance.',
    'Maintenance becomes repair work when the inspection finds broken tiles, loose ridge caps, failed fixings, corroded components or leaking junctions. We explain the defects and include the appropriate local replacement or repair work in the maintenance scope.'
  ],
  'roof-cleaning-painting': [
    'We inspect the roof material, existing coating, surface condition, damaged components and drainage before specifying cleaning or painting. Repairs come first; the cleaning method, preparation and coating system must suit the actual substrate and existing finish.',
    'Yes. Tile and metal roofs need different preparation and coating considerations. We check tile condition and porosity or the metal roof finish and corrosion, address repair defects and select compatible cleaning and coating methods for the surface.',
    'Tell us whether the roof is tile or metal, its existing finish, any previous coating and whether there are leaks or damaged components. Photographs help show the roof area and surface condition. We inspect the property and provide a scope covering repairs, preparation and the proposed finish.'
  ],
  'commercial-roof-repairs': [
    'The building use, roof material, affected areas, access arrangements and operating hours help us plan commercial repairs. We also review recurring leaks, previous work and equipment or penetrations on the roof, then coordinate the repair scope with the building manager.',
    'Yes. Our commercial service covers connected sheet, flashing, penetration, gutter and downpipe defects. We inspect the roof and drainage route, identify the affected components and organise the repair sequence around access and the property operation.',
    'Provide an affected-area plan or room locations, photographs, leak timing, previous repair records and a site contact. Tell us about restricted access and operating requirements. We use these details to plan inspection, explain the work and arrange practical attendance.'
  ],
  'storm-damage-roof-repairs': [
    'Record the time of the event, affected rooms and any new water entry or displaced roof material visible from a safe position. Existing photographs of the roof and damage help us prepare. Urgent enquiries are prioritised; attendance is arranged promptly when weather, site access and safety conditions allow.',
    'A photograph helps us prepare, and our inspection establishes the connected damage and repair scope. We check the roof covering, exposed junctions, roof-void details where accessible and drainage, then organise temporary protection or repair work according to the condition found.',
    'Tell us about active water entry, electrical fittings near water, fallen debris and any restricted or unsafe access. Keep clear of affected areas. Our team uses the information to plan attendance and carry out protection and repair work when site conditions permit.'
  ],
  'roof-inspection': [
    'A roof inspection checks the covering, ridges, valleys, flashings, penetrations, gutters and downpipes, with accessible under-roof details where relevant. We identify defects, connect them to leaks or maintenance concerns and explain the repair priorities for the property.',
    'The quote should identify the inspected defects, affected areas, materials, repair method, access requirements and included work. Our team explains which repairs are a priority and which maintenance items can be planned separately.',
    'Arrange inspection before the wet season to identify damaged tiles, loose capping, deteriorated flashings and blocked drainage routes. We check gutters and outlets, address the identified roof defects and help organise ongoing maintenance suited to the property.'
  ]
};

export const serviceLeads = {
  'roof-repairs': 'We inspect and repair Perth tile and metal roofs, tracing leaks and restoring damaged tiles, ridges, valleys, flashings and roof-edge drainage. Our team defines the work required and coordinates the repairs for your property.',
  'roof-leak-repairs': 'We trace roof leaks to their source and repair damaged tiles, metal sheets, fasteners, valleys and flashings. From ceiling stains to recurring rainwater entry, our Perth team checks the connected water path and completes the required roof repairs.',
  'tile-roof-repairs': 'We repair concrete and terracotta tile roofs across Perth, replacing damaged tiles and restoring adjoining ridge, valley and flashing details. Our inspection identifies the repair area and compatible materials for the roof.',
  'metal-roof-repairs': 'We repair Perth metal roofs, including corrugated sheets, fasteners, washers, ridge and hip capping, flashings and penetrations. Our team checks corrosion, damaged connections and water paths before completing the appropriate local repairs.',
  'ridge-capping-repointing': 'We repair ridge capping and carry out repointing and rebedding for Perth tiled roofs. Our team checks cap stability, bedding and adjoining tiles, then restores the affected ridge or hip runs.',
  'flashing-repairs': 'We repair and replace roof valleys and flashings at walls, chimneys, skylights and penetrations. Our Perth team checks the adjoining roof material and drainage path and forms the repair detail to suit the junction.',
  'gutter-repairs': 'We repair leaking joints, sagging sections, corroded guttering and outlet connections across Perth. Our team checks roof-edge drainage, gutter supports and connected downpipes to restore the affected water route.',
  'gutters-downpipes': 'We inspect, clean and repair connected gutters and downpipes across Perth. From overflow at the roof edge to leaking pipe connections, we identify the drainage defect and organise the necessary repairs.',
  'downpipe-repairs': 'We repair downpipe joints, brackets, damaged sections and gutter outlet connections across Perth. Our team checks the visible drainage route and restores secure connections and supports.',
  'roof-maintenance': 'We maintain Perth tile and metal roofs through inspection, drainage clearing and targeted repairs. Our team prioritises tiles, fasteners, ridges, valleys and flashings according to the condition of your roof.',
  'roof-inspection': 'We inspect Perth roofs for leaks, damaged coverings, ridge and flashing defects and drainage problems. Our team explains the findings and provides clear repair and maintenance priorities.',
  'roof-cleaning-painting': 'We provide roof cleaning and painting services in Perth, with repairs and surface preparation planned around the roof material. Our team checks the existing finish and specifies compatible cleaning and coating work.',
  'commercial-roof-repairs': 'We repair roofs for Perth businesses and managed properties, covering sheets, flashings, penetrations and drainage. Our team coordinates inspection, site access and repair work with the building manager.',
  'storm-damage-roof-repairs': 'We assess storm-related roof damage and organise protection and repairs for affected coverings, junctions and drainage. Urgent enquiries are prioritised; attendance is arranged promptly when weather, site access and safety conditions allow.'
};
import { githubServiceAnswers } from './github-service-answers.mjs';
const retainedServiceTitles = {
  'roof-repairs':'Roof Repairs Perth', 'roof-leak-repairs':'Roof Leak Repairs Perth',
  'tile-roof-repairs':'Tile Roof Repairs Perth', 'metal-roof-repairs':'Metal Roof Repairs Perth',
  'ridge-capping-repointing':'Ridge Capping Repairs Perth', 'flashing-repairs':'Roof Valleys & Flashing Repairs Perth',
  'gutters-downpipes':'Gutters & Downpipes Perth', 'downpipe-repairs':'Downpipe Repairs Perth',
  'roof-inspection':'Roof Inspection & Maintenance Perth', 'gutter-repairs':'Gutter Repairs Perth',
  'roof-maintenance':'Roof Maintenance Perth', 'storm-damage-roof-repairs':'Storm Damage Roof Repairs Perth'
};
for (const [route,title] of Object.entries(retainedServiceTitles)) {
  if (!githubServiceAnswers[title]) throw new Error(`Missing retained service answers: ${title}`);
  serviceAnswers[route] = githubServiceAnswers[title];
}
